AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - '*.spec'
    - 'Rakefile'
  NewCops: enable

Style/ClassAndModuleChildren:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Layout/LineLength:
  Max: 190

Style/RescueModifier:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
